### ISSUE TITLE
Save Feature Broken

### ISSUE THREAD

**Issue by griimick** [karan-hashtag/pySFEditor#1]
After the commit which added Line Numbers and Close button to each tab, the Save Feature Broke.

> Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Soumik Pradhan\AppData\Local\Programs\Python\Python35\lib\tkinter\__init__.py", line 1550, in __call__
    return self.func(*args)
  File "D:\Users\Soumik Pradhan\Documents\GitHub\pySFEditor\pySFEditor.py", line 433, in save_file
    self.save_as()
  File "D:\Users\Soumik Pradhan\Documents\GitHub\pySFEditor\pySFEditor.py", line 448, in save_as
    self.editornotebook.tab(currenteditor, text=filename)
  File "C:\Users\Soumik Pradhan\AppData\Local\Programs\Python\Python35\lib\tkinter\ttk.py", line 897, in tab
    return _val_or_dict(self.tk, kw, self._w, "tab", tab_id)
  File "C:\Users\Soumik Pradhan\AppData\Local\Programs\Python\Python35\lib\tkinter\ttk.py", line 297, in _val_or_dict
    res = tk.call(*(args + options))
_tkinter.TclError: .2258871829112.2258871829672.2258871933808.2258871934368 is not managed by .2258871829112.2258871829672
[Finished in 29.1s]

**Comment by karanev** [comment]
Its probably because of the way editor is organised now earlier tabs(notebooks) used to include editor but after commit I change their organisation to better complement scrollbars. Now notebooks contain tab and tab contains editor

**Comment by karanev** [comment]
fixed it
use this
`self.editornotebook.tab(currenttab, text=os.path.basename(filename))`
instead of `self.editornotebook.tab(currenteditor, text=filename)` at line 356
